---
title: "Test Presentation"
subtitle: "A test presentation with some features"
author: Vladislav Morozov  
format:
  revealjs:
    slide-number: true
    sc-sb-title: true
    logo: ../themes/favicon.ico
    footer: Test Footer
    footer-logo-link: "https://vladislav-morozov.github.io/econometrics-2/"
    theme: ../themes/slides_theme.scss
slide-level: 3
title-slide-attributes:
    data-background-color: "#045D5D"
filters:
  - reveal-header 
embed-resources: true
include-in-header: ../themes/mathjax.html 
highlight-style: tango
---

# SECTION {background="#014D4E"}

## SUBSECTION {background="#43464B"}

### Hello There

This presentation shows a few slides made by Quarto and [Reveal.js](https://revealjs.com) along with header logo and header text which are easily embedded by using the Quarto filter `reveal-header`

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

### Slide Backgrounds {background="#43464B"}

This slide is created using the `background` attribute (`{background="#43464B"}`) and as you can see that header text color is different (difference is trivial though) than before.

if you want you can change the color of the header text for slides with `background` attribute using css class `.inverse-header`. For example,

~~~
.inverse-header {
  color: #c1c1c1 !important;
}
~~~

Here using `!important` is important :p.

::: footer
Learn more: [Slide Backgrounds](https://quarto.org/docs/presentations/revealjs/#color-backgrounds)
:::

### Slide Backgrounds {background="#43464B"}



This slide contains a header div, therefore it has a header.

::: footer
Learn more: [Slide Backgrounds](https://quarto.org/docs/presentations/revealjs/#color-backgrounds)
:::

### Lists

Ordered: 

1. A o
2. o


Other:

- f
  - subfirst
  - subsecond 
- second
- third


## Code

### Executable Code
 

```{python}
#| echo: true
#| fig-width: 10
#| fig-height: 4.5

1+1
```

::: footer
Learn more: [Executable Code](https://quarto.org/docs/presentations/revealjs/#executable-code)
:::


### Line Highlighting
 
``` {.python code-line-numbers="4-5|7|10"} 

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```



### Code with Columns {background="#43464B"}

```{python}  
#| echo: true 
#| output-location: column

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

::: footer
Learn more: [Line Highlighting](https://quarto.org/docs/presentations/revealjs/#line-highlighting)
:::


# Other Section

## Other Subsection


### Slide

Slid

# Math 

## Equations

### Some equations

Outcome is $y_{it}$
$$
\E[y_{it}|x_{it}= x] = f(x)
$$

### Some equations 2 {background="#43464B"}

Outcome is $y_{it}$
$$
\E[y_{it}|x_{it}= x] = f(x)
$$