<!DOCTYPE html>
<html lang="en"><head>
<link href="../../themes/favicon.ico" rel="icon">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0de45b8b5f35a93596f1d788d60c4c11.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/quarto-contrib/reveal-header-1.0.0/add_header.js" defer="true"></script>
<link href="../../site_libs/quarto-contrib/reveal-header-1.0.0/add_header.css" rel="stylesheet">
<script src="../../site_libs/quarto-contrib/sc-sb-title-1.0.0/sc_sb_title.js" defer="true"></script>
<link href="../../site_libs/quarto-contrib/grid-no-htext-1.0.0/grid_no_htext.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Vladislav Morozov">
  <title>Advanced Econometrics – Classification</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {  background-color: #f8f8f8; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ef2929; } /* Alert */
    code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #204a87; } /* Attribute */
    code span.bn { color: #0000cf; } /* BaseN */
    code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4e9a06; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #8f5902; font-style: italic; } /* Comment */
    code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
    code span.dt { color: #204a87; } /* DataType */
    code span.dv { color: #0000cf; } /* DecVal */
    code span.er { color: #a40000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #0000cf; } /* Float */
    code span.fu { color: #204a87; font-weight: bold; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
    code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
    code span.ot { color: #8f5902; } /* Other */
    code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
    code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
    code span.ss { color: #4e9a06; } /* SpecialString */
    code span.st { color: #4e9a06; } /* String */
    code span.va { color: #000000; } /* Variable */
    code span.vs { color: #4e9a06; } /* VerbatimString */
    code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-cb5537517b990794adf0c72e32550bcc.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
   

  <!-- This is what works with Quarto and MathJax 3+ -->

  <script>

    MathJax = {

      tex: {

        tags: 'ams',  // should be 'ams', 'none', or 'all'

        macros: {

          vect: ["\\mathbf{#1}", 1],

          mat: ["\\mathbf{#1}", 1], 

  

          bA: "\\boldsymbol{A}",

          bB: "\\boldsymbol{B}",

          bC: "\\boldsymbol{C}",

          bD: "\\boldsymbol{D}",

          bE: "\\boldsymbol{E}",

          bF: "\\boldsymbol{F}",

          bG: "\\boldsymbol{G}",

          bH: "\\boldsymbol{H}",

          bI: "\\boldsymbol{I}",

          bJ: "\\boldsymbol{J}",

          bK: "\\boldsymbol{K}",

          bL: "\\boldsymbol{L}",

          bM: "\\boldsymbol{M}",

          bN: "\\boldsymbol{N}",

          bP: "\\boldsymbol{P}",

          bQ: "\\boldsymbol{Q}",

          bR: "\\boldsymbol{R}",

          bS: "\\boldsymbol{S}",

          bT: "\\boldsymbol{T}",

          bU: "\\boldsymbol{U}",

          bV: "\\boldsymbol{V}",

          bW: "\\boldsymbol{W}",

          bX: "\\boldsymbol{X}",

          bY: "\\boldsymbol{Y}",

          bZ: "\\boldsymbol{Z}",

          ba: "\\boldsymbol{a}",

          bb: "\\boldsymbol{b}",

          bc: "\\boldsymbol{c}",

          bd: "\\boldsymbol{d}",

          be: "\\boldsymbol{e}",

          bg: "\\boldsymbol{g}",

          bh: "\\boldsymbol{h}",

          bi: "\\boldsymbol{\\imath}",

          bm: "\\boldsymbol{m}",

          bp: "\\boldsymbol{p}",

          bq: "\\boldsymbol{q}",

          br: "\\boldsymbol{r}",

          bs: "\\boldsymbol{s}",

          bt: "\\boldsymbol{t}",

          bu: "\\boldsymbol{u}",

          bv: "\\boldsymbol{v}",

          bw: "\\boldsymbol{w}",

          bx: "\\boldsymbol{x}",

          by: "\\boldsymbol{y}",

  

          Acal: "\\mathcal{A}",

          Bcal: "\\mathcal{B}",

          Ccal: "\\mathcal{C}",

          Dcal: "\\mathcal{D}",

          Ecal: "\\mathcal{E}",

          Fcal: "\\mathcal{F}",

          Gcal: "\\mathcal{G}",

          Hcal: "\\mathcal{H}",

          Ical: "\\mathcal{I}",

          Jcal: "\\mathcal{J}",

          Kcal: "\\mathcal{K}",

          Lcal: "\\mathcal{L}",

          Mcal: "\\mathcal{M}",

          Ncal: "\\mathcal{N}",

          Ocal: "\\mathcal{O}",

          Pcal: "\\mathcal{P}",

          Qcal: "\\mathcal{Q}",

          Rcal: "\\mathcal{R}",

          Scal: "\\mathcal{S}",

          Tcal: "\\mathcal{T}",

          Ucal: "\\mathcal{U}",

          Vcal: "\\mathcal{V}",

          Wcal: "\\mathcal{W}",

          Xcal: "\\mathcal{X}",

          Ycal: "\\mathcal{Y}",

          Zcal: "\\mathcal{Z}",

  

          A: "\\mathbb{A}",

          B: "\\mathbb{B}",

          C: "\\mathbb{C}",

          D: "\\mathbb{D}",

          E: "\\mathbb{E}",

          F: "\\mathbb{F}",

          G: "\\mathbb{G}",

          H: "\\mathbb{H}",

          I: "\\mathbb{I}",

          J: "\\mathbb{J}",

          K: "\\mathbb{K}",

          L: "\\mathbb{L}",

          M: "\\mathbb{M}",

          N: "\\mathbb{N}",

          O: "\\mathbb{O}",

          P: "\\mathbb{P}",

          Q: "\\mathbb{Q}",

          R: "\\mathbb{R}",

          S: "\\mathbb{S}",

          T: "\\mathbb{T}",

          U: "\\mathbb{U}",

          V: "\\mathbb{V}",

          W: "\\mathbb{W}",

          X: "\\mathbb{X}",

          Y: "\\mathbb{Y}",

          Z: "\\mathbb{Z}",

  

          bAlpha: "\\boldsymbol{\\Alpha}",

          bBeta: "\\boldsymbol{\\beta}",

          bDelta: "\\boldsymbol{\\delta}",

          bEta: "\\boldsymbol{\\eta}",

          bGamma: "\\boldsymbol{\\Gamma}",

          bLambda: "\\boldsymbol{\\Lambda}",

          bOmega: "\\boldsymbol{\\Omega}",

          bPhi: "\\boldsymbol{\\Phi}",

          bPi: "\\boldsymbol{\\Pi}",

          bPsi: "\\boldsymbol{\\Psi}",

          bSigma: "\\boldsymbol{\\Sigma}",

          bTau: "\\boldsymbol{\\tau}",

          bXi: "\\boldsymbol{\\Xi}",

          bbeta: "\\boldsymbol{\\beta}",

          bdelta: "\\boldsymbol{\\delta}",

          blambda: "\\boldsymbol{\\lambda}",

          bmu: "\\boldsymbol{\\mu}",

          bphi: "\\boldsymbol{\\phi}",

          bpi: "\\boldsymbol{\\pi}",

          bpsi: "\\boldsymbol{\\psi}",

          brho: "\\boldsymbol{\\rho}",

          balpha: "\\boldsymbol{\\alpha}",

          bsigma: "\\boldsymbol{\\sigma}",

          btau: "\\boldsymbol{\\tau}",

          bxi: "\\boldsymbol{\\xi}",

          bEta: "\\boldsymbol{\\eta}",

          bPhi: "\\boldsymbol{\\Phi}",

          bPi: "\\boldsymbol{\\Pi}",

          bPsi: "\\boldsymbol{\\Psi}",

          bXi: "\\boldsymbol{\\Xi}",

          blambda: "\\boldsymbol{\\lambda}",

          bmu: "\\boldsymbol{\\mu}",

          bphi: "\\boldsymbol{\\phi}",

          bpi: "\\boldsymbol{\\pi}",

          bpsi: "\\boldsymbol{\\psi}",

          brho: "\\boldsymbol{\\rho}",

          bsigma: "\\boldsymbol{\\sigma}",

          btheta: "\\boldsymbol{\\theta}",

          bgamma: "\\boldsymbol{\\gamma}",  

          

          curl: ["\\left\\lbrace#1\\right\\rbrace", 1],

          floor: ["\\left\\lfloor#1\\right\\rfloor", 1],

          ceil: ["\\left\\lceil#1\\right\\rceil", 1],

          abs: ["\\left\\lvert#1\\right\\rvert", 1],

          norm: ["\\left\\lVert#1\\right\\rVert", 1],

  

          avar: "\\mathrm{avar}",

          var: "\\mathrm{var}",

          cov: "\\mathrm{cov}",

  

          argmin: "\\operatorname*{argmin}",

          argmax: "\\operatorname*{argmax}",

          argsup: "\\operatorname*{argsup}",

          arginf: "\\operatorname*{arginf}",

        }

      }

    };

  </script>
  <meta name="description" content="Basics of binary and multiclass classification: evaluation metrics; logistic, support vector, and random forest classifiers (lecture note slides)">
<meta property="og:title" content="Classification – Advanced Econometrics">
<meta property="og:description" content="Basics of binary and multiclass classification: evaluation metrics; logistic, support vector, and random forest classifiers (lecture note slides)">
<meta property="og:site_name" content="Advanced Econometrics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#045D5D" data-footer="" class="quarto-title-block center">
  <h1 class="title">Classification</h1>
  <p class="subtitle">Basics of Binary and Multiclass Classification</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Vladislav Morozov 
</div>
</div>
</div>

</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Contents</h2>
<ul>
<li class="fragment"><a href="#/introduction" id="/toc-introduction">Introduction</a></li>
<li class="fragment"><a href="#/classification" id="/toc-classification">Classification</a></li>
<li class="fragment"><a href="#/binary-classification-algorithms" id="/toc-binary-classification-algorithms">Binary Classification Algorithms</a></li>
<li class="fragment"><a href="#/evaluating-classifiers" id="/toc-evaluating-classifiers">Evaluating Classifiers</a></li>
<li class="fragment"><a href="#/basics-of-multiclass-classification" id="/toc-basics-of-multiclass-classification">Basics of Multiclass Classification</a></li>
<li class="fragment"><a href="#/recap-and-conclusions" id="/toc-recap-and-conclusions">Recap and Conclusions</a></li>
</ul>
</nav>
</section>
<section>
<section id="introduction" class="title-slide slide level2 center" data-background="#00100F">
<h2>Introduction</h2>

</section>
<section id="lecture-info" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Lecture Info</h3>

</section>
<section id="learning-outcomes" class="slide level4">
<h4>Learning Outcomes</h4>
<p>In this lecture we take a look at classification</p>
<p><br></p>
<p>By the end, you should be able to</p>
<ol type="1">
<li class="fragment">Talk about binary and multiclass classification problems</li>
<li class="fragment">Describe and use several leading classification algorithms</li>
<li class="fragment">Evaluate classifiers with a variety of metrics</li>
</ol>
</section>
<section id="references" class="slide level4">
<h4>References</h4>
<p><br></p>
<div>
<ul>
<li>Chapters 4, 8-9 in <span class="citation" data-cites="James2023IntroductionStatisticalLearning">James et al. (<a href="#/references-1" role="doc-biblioref" onclick="">2023</a>)</span></li>
<li><a href="https://scikit-learn.org/stable/user_guide.html"><code>scikit-learn</code> User Guide</a>: 1.1.11, 1.5, 1.10-1.11</li>
<li>Deeper: chapter 4, 9, 15 in <span class="citation" data-cites="Hastie2009ElementsStatisticalLearning">Hastie, Tibshirani, and Friedman (<a href="#/references-1" role="doc-biblioref" onclick="">2009</a>)</span></li>
</ul>
</div>
</section>
<section id="imports" class="slide level4 scrollable">
<h4>Imports</h4>
<div id="63d167be" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-2"><a></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a></a><span class="im">import</span> pandas <span class="im">as</span> pd </span>
<span id="cb1-4"><a></a></span>
<span id="cb1-5"><a></a><span class="co"># Obtaining data from openML</span></span>
<span id="cb1-6"><a></a><span class="im">from</span> sklearn.datasets <span class="im">import</span> fetch_openml</span>
<span id="cb1-7"><a></a></span>
<span id="cb1-8"><a></a><span class="co"># Dummy classifier for benchmarking</span></span>
<span id="cb1-9"><a></a><span class="im">from</span> sklearn.dummy <span class="im">import</span> DummyClassifier</span>
<span id="cb1-10"><a></a></span>
<span id="cb1-11"><a></a><span class="co"># Classification random forest</span></span>
<span id="cb1-12"><a></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb1-13"><a></a></span>
<span id="cb1-14"><a></a><span class="co"># Logistic regression and SVM classifiers</span></span>
<span id="cb1-15"><a></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> (</span>
<span id="cb1-16"><a></a>  LogisticRegression,</span>
<span id="cb1-17"><a></a>  SGDClassifier,</span>
<span id="cb1-18"><a></a>)</span>
<span id="cb1-19"><a></a></span>
<span id="cb1-20"><a></a><span class="co"># Metrics for evaluating classifiers</span></span>
<span id="cb1-21"><a></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> (</span>
<span id="cb1-22"><a></a>  confusion_matrix,</span>
<span id="cb1-23"><a></a>  ConfusionMatrixDisplay,</span>
<span id="cb1-24"><a></a>  f1_score,</span>
<span id="cb1-25"><a></a>  precision_recall_curve,</span>
<span id="cb1-26"><a></a>  precision_score,</span>
<span id="cb1-27"><a></a>  recall_score,</span>
<span id="cb1-28"><a></a>  roc_auc_score,</span>
<span id="cb1-29"><a></a>  roc_curve,</span>
<span id="cb1-30"><a></a>)</span>
<span id="cb1-31"><a></a></span>
<span id="cb1-32"><a></a><span class="co"># Cross-validation computation of classifier properties</span></span>
<span id="cb1-33"><a></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> (</span>
<span id="cb1-34"><a></a>  cross_val_predict,</span>
<span id="cb1-35"><a></a>  cross_val_score, </span>
<span id="cb1-36"><a></a>)</span>
<span id="cb1-37"><a></a></span>
<span id="cb1-38"><a></a><span class="co"># Pipelines</span></span>
<span id="cb1-39"><a></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb1-40"><a></a></span>
<span id="cb1-41"><a></a><span class="co"># Feature scaler</span></span>
<span id="cb1-42"><a></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

<section id="empirical-setup" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Empirical Setup</h3>

</section>
<section id="motivation-i" class="slide level4">
<h4>Motivation I</h4>
<p>Suppose that you</p>
<ul>
<li class="fragment">Want to send a postcard to a friend</li>
<li class="fragment">Write the address by hand</li>
</ul>
<p><br></p>
<div class="fragment">
<div class="rounded-box">
<p>How do the post offices know where to send the postcard?</p>
</div>
</div>
</section>
<section id="motivation-ii" class="slide level4">
<h4>Motivation II</h4>
<ul>
<li class="fragment">Almost all handwritten addresses are recognized automatically</li>
<li class="fragment">Example of computer vision <em>classification problem</em>
<ul>
<li class="fragment">Features: pixels of scanned image</li>
<li class="fragment">Labels: letters and numbers</li>
<li class="fragment">Goal: recognize the letters and numbers as accurately as possible</li>
</ul></li>
</ul>
<div class="fragment">
<div class="rounded-box">
<p>Today: focus on recognized handwritten numbers with a nice standardized dataset</p>
</div>
<div class="footer">

</div>
</div>
</section>
<section id="our-empirical-example" class="slide level4">
<h4>Our Empirical Example</h4>
<p>Will use MNIST data — <em>modified National Institute of Standards and Technology database</em></p>
<ul>
<li class="fragment">Large dataset of handwritten digits</li>
<li class="fragment">A fundamental dataset: one of the first datasets new methods are tried on</li>
</ul>
<div class="fragment">
<p><br></p>
<p>Benchmark to remember: humans make around 1.5% mistakes on it <span class="citation" data-cites="Simard1992EfficientPatternRecognition">(<a href="#/references-1" role="doc-biblioref" onclick="">Simard, Le Cun, and Denker 1992</a>)</span></p>
<div class="footer">

</div>
</div>
</section>
<section id="obtaining-the-data" class="slide level4">
<h4>Obtaining the Data</h4>
<p><br></p>
<ul>
<li class="fragment">Can obtain the full dataset from <a href="https://www.openml.org/">openML</a></li>
<li class="fragment"><code>scikit-learn</code> even offers a <code>fetch_openml()</code> function for convenience</li>
</ul>
<div id="41fc8969" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a></a>mnist <span class="op">=</span> fetch_openml(</span>
<span id="cb2-2"><a></a>    <span class="st">"mnist_784"</span>,</span>
<span id="cb2-3"><a></a>    as_frame<span class="op">=</span><span class="va">False</span>,          <span class="co"># Return NumPy arrays instead of pd.DataFrame</span></span>
<span id="cb2-4"><a></a>    data_home<span class="op">=</span>data_path, </span>
<span id="cb2-5"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-description" class="slide level4 scrollable">
<h4>Data Description</h4>
<p>Remember to check your data and perform EDA!</p>
<div id="4e4e413c" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a></a><span class="bu">print</span>(mnist.DESCR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>**Author**: Yann LeCun, Corinna Cortes, Christopher J.C. Burges  
**Source**: [MNIST Website](http://yann.lecun.com/exdb/mnist/) - Date unknown  
**Please cite**:  

The MNIST database of handwritten digits with 784 features, raw data available at: http://yann.lecun.com/exdb/mnist/. It can be split in a training set of the first 60,000 examples, and a test set of 10,000 examples  

It is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image. It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting. The original black and white (bilevel) images from NIST were size normalized to fit in a 20x20 pixel box while preserving their aspect ratio. The resulting images contain grey levels as a result of the anti-aliasing technique used by the normalization algorithm. the images were centered in a 28x28 image by computing the center of mass of the pixels, and translating the image so as to position this point at the center of the 28x28 field.  

With some classification methods (particularly template-based methods, such as SVM and K-nearest neighbors), the error rate improves when the digits are centered by bounding box rather than center of mass. If you do this kind of pre-processing, you should report it in your publications. The MNIST database was constructed from NIST's NIST originally designated SD-3 as their training set and SD-1 as their test set. However, SD-3 is much cleaner and easier to recognize than SD-1. The reason for this can be found on the fact that SD-3 was collected among Census Bureau employees, while SD-1 was collected among high-school students. Drawing sensible conclusions from learning experiments requires that the result be independent of the choice of training set and test among the complete set of samples. Therefore it was necessary to build a new database by mixing NIST's datasets.  

The MNIST training set is composed of 30,000 patterns from SD-3 and 30,000 patterns from SD-1. Our test set was composed of 5,000 patterns from SD-3 and 5,000 patterns from SD-1. The 60,000 pattern training set contained examples from approximately 250 writers. We made sure that the sets of writers of the training set and test set were disjoint. SD-1 contains 58,527 digit images written by 500 different writers. In contrast to SD-3, where blocks of data from each writer appeared in sequence, the data in SD-1 is scrambled. Writer identities for SD-1 is available and we used this information to unscramble the writers. We then split SD-1 in two: characters written by the first 250 writers went into our new training set. The remaining 250 writers were placed in our test set. Thus we had two sets with nearly 30,000 examples each. The new training set was completed with enough examples from SD-3, starting at pattern # 0, to make a full set of 60,000 training patterns. Similarly, the new test set was completed with SD-3 examples starting at pattern # 35,000 to make a full set with 60,000 test patterns. Only a subset of 10,000 test images (5,000 from SD-1 and 5,000 from SD-3) is available on this site. The full 60,000 sample training set is available.

Downloaded from openml.org.</code></pre>
</div>
</div>
<div class="footer">

</div>
</section>
<section id="splitting-the-data" class="slide level4">
<h4>Splitting the Data</h4>
<p>Split the data manually into <code>X</code> and <code>y</code> arrays</p>
<div id="ad7e72eb" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a></a>X, y <span class="op">=</span> mnist.data, mnist.target </span>
<span id="cb5-2"><a></a><span class="bu">print</span>(y[<span class="dv">0</span>:<span class="dv">10</span>])    <span class="co"># Labels of first ten observations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['5' '0' '4' '1' '9' '2' '1' '3' '1' '4']</code></pre>
</div>
</div>
<p><br></p>
<p>Data already sorted into training and test split (see <code>DESCR</code>)</p>
<div id="c69af83c" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a></a>X, y <span class="op">=</span> mnist.data, mnist.target</span>
<span id="cb7-2"><a></a>X_train, X_test, y_train, y_test <span class="op">=</span> <span class="op">\</span></span>
<span id="cb7-3"><a></a>    X[:<span class="dv">60000</span>], X[<span class="dv">60000</span>:], y[:<span class="dv">60000</span>], y[<span class="dv">60000</span>:]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li class="fragment">10k training examples</li>
<li class="fragment">There are extended datasets with bigger test sets</li>
</ul>
</section>
<section id="visualizing-the-data" class="slide level4">
<h4>Visualizing the Data</h4>
<div class="columns">
<div class="column" style="width:50%;">
<div id="f3ad4177" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="classification_files/figure-revealjs/cell-8-output-1.png" width="540" height="537"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li class="fragment">Image: selection of 100 observations in data</li>
<li class="fragment">Those are <span class="math inline">\(\bx\)</span>; <span class="math inline">\(y\)</span> are labels like <code>'1'</code> or <code>'7'</code></li>
<li class="fragment">Data reshaped; original form of data: 784-vectors (note: <span class="math inline">\(784=28^2\)</span>)</li>
</ul>
<div id="ee0ed5fb" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a></a>X[<span class="dv">0</span>, :].shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>(784,)</code></pre>
</div>
</div>
</div></div>
<div class="footer">

</div>
</section>
<section id="lecture-plan" class="slide level4">
<h4>Lecture Plan</h4>
<div class="rounded-box">
<p>Will focus on</p>
<ul>
<li class="fragment">Basic learning algorithms for binary and multiclass classification</li>
<li class="fragment">Evaluating classifiers</li>
</ul>
</div>
<p><br></p>
<div class="fragment">
<p>We will not talk much about EDA, data preparation, etc. (see previous two lectures), but those are equally important for classification!</p>
</div>
</section>
</section>
<section>
<section id="classification" class="title-slide slide level2 center" data-background="#00100F">
<h2>Classification</h2>

</section>
<section id="binary-vs.-multiclass-classification" class="slide level4">
<h4>Binary vs.&nbsp;Multiclass Classification</h4>
<p>Recall:</p>
<div class="rounded-box">
<ul>
<li class="fragment">In <span class="highlight">binary</span> classification the label takes on 2 possible values</li>
<li class="fragment">In <span class="highlight">multiclass</span> classification the label takes on <span class="math inline">\(k&gt;2\)</span> possible values</li>
</ul>
</div>
<p>The labels can be <span class="highlight">ordered</span> (e.g.&nbsp;“big”, “medium”, “small”) or <span class="highlight">unordered</span> (e.g.&nbsp;“cat”, “dog”)</p>
<div class="footer">
<p>Division between multiclass classification with ordered numerical labels and large <span class="math inline">\(k\)</span> and regression not always clear</p>
</div>
</section>
<section id="single-output-vs.-multi-output-classification" class="slide level4">
<h4>Single-Output vs.&nbsp;Multi-Output Classification</h4>
<p>Another axis of difference between problems:</p>
<div class="rounded-box">
<ul>
<li class="fragment">In <span class="highlight">single-output</span> problems the label <span class="math inline">\(Y\)</span> is one-dimensional</li>
<li class="fragment">In <span class="highlight">multi-output</span> problems <span class="math inline">\(Y\)</span> can be multidimensional</li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p>Example of multi-output problem: labeling photos by their contents. Many kinds of items can be present in photos <span class="highlight">at the same time</span></p>
</div>
</section>
<section id="indicator-risk" class="slide level4">
<h4>Indicator Risk</h4>
<p>Recall: should start the learning problem by choosing a suitable criterion — ideally a risk function</p>
<div class="fragment">
<p><br></p>
<p>Already met the indicator risk: <span class="math display">\[
R(h) = \E\Big[\I\curl{Y\neq h(\bX)} \Big] = P\Big(Y\neq h(\bX)\Big)
\]</span></p>
<p><span class="math inline">\(1-R(h)\)</span> is known as <span class="highlight">accuracy</span></p>
</div>
</section>
<section id="drawbacks-of-accuracy" class="slide level4">
<h4>Drawbacks of Accuracy</h4>
<ul>
<li class="fragment">Treats all errors equally, which might not be the right thing in a context</li>
<li class="fragment">Problematic with unbalanced classes
<ul>
<li class="fragment">Example: 1 unit of class <code>0</code> per 999 units of class <code>1</code></li>
<li class="fragment">A classifier that always predicts <code>1</code> has 99.9% accuracy, but is 0% right on class <code>0</code></li>
</ul></li>
<li class="fragment">Often impossible to minimize (<span class="math inline">\(\Rightarrow\)</span> surrogate losses)</li>
</ul>
<div class="footer">
<p>Accuracy has some more issues, see <a href="https://stats.stackexchange.com/questions/312780/why-is-accuracy-not-the-best-measure-for-assessing-classification-models">here</a></p>
</div>
</section>
<section id="other-metrics" class="slide level4">
<h4>Other Metrics</h4>
<p><span class="math inline">\(\Rightarrow\)</span> very common to consider various metrics</p>
<ul>
<li class="fragment">Criteria expressable as risk functions (e.g.&nbsp;weighted losses with potentially different costs of different errors)</li>
<li class="fragment">Ratio metrics such as precision, recall</li>
</ul>
<div class="fragment">
<p>Classifiers may be <span class="highlight">tuned</span>:</p>
<ul>
<li class="fragment">Usually first found based on some tractable objetive function (e.g.&nbsp;QML)</li>
<li class="fragment">Then tuned to optimize specific aspects</li>
</ul>
</div>
</section></section>
<section>
<section id="binary-classification-algorithms" class="title-slide slide level2 center" data-background="#00100F">
<h2>Binary Classification Algorithms</h2>

</section>
<section id="setting-labels-in-binary-classification" class="slide level4">
<h4>Setting: Labels in Binary Classification</h4>
<p>Two equivalent ways of expressing classes:</p>
<ul>
<li class="fragment"><p>Labels expressed as 0 and 1 <span class="math display">\[
Y \in \curl{0, 1}
\]</span> Common to logit and generalizations (including NNs)</p></li>
<li class="fragment"><p>Labels expressed as <span class="math inline">\(-1\)</span> and 1 <span class="math display">\[
Y\in \curl{-1, 1}
\]</span> Often see with support vector machines</p></li>
</ul>
<div class="footer">
<p>Does not matter in practice, but sometimes one or the other is more convenient in theory</p>
</div>
</section>
<section id="empirical-example" class="slide level4">
<h4>Empirical Example</h4>
<p>Our example based on MNIST data:</p>
<div class="rounded-box">
<p>Detect that a given collection of pixels represents a <code>'0'</code> or not</p>
</div>
<p><br></p>
<p>Create the new binary labels:</p>
<div id="c7eb86dc" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a></a>y_train_0 <span class="op">=</span> (y_train <span class="op">==</span> <span class="st">'0'</span>)</span>
<span id="cb10-2"><a></a>y_test_0 <span class="op">=</span> (y_test <span class="op">==</span> <span class="st">'0'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="linear-classifiers" class="slide level4">
<h4>Linear Classifiers</h4>
<p>Like with regression one can have linear and nonlinear classifiers</p>
<p><br></p>
<p>Linear classifiers generally take form <span id="eq-linear-classifier"><span class="math display">\[
\Hcal = \curl{h(\bx) = \I\curl{f\left(\varphi(\bx)'\bbeta\right) &gt; \theta}: \bbeta\in \R^{\dim(\varphi(\bbeta))} }
\tag{1}\]</span></span></p>
<ul>
<li class="fragment"><span class="math inline">\(f(\cdot)\)</span> and <span class="math inline">\(\varphi(\cdot)\)</span> are known functions</li>
<li class="fragment"><span class="math inline">\(\theta\)</span> is a tunable threshold</li>
</ul>
</section>
<section id="examples-of-linear-classifiers-logit" class="slide level4">
<h4>Examples of Linear Classifiers: Logit</h4>
<p>Logistic regression (<code>0</code>, <code>1</code> labels) <span class="math display">\[
\begin{aligned}
h(\bx) &amp; = \I\curl{  \Lambda( \varphi(\bx)'\bbeta  ) \geq \theta  }, \\
\Lambda(x) &amp; = \dfrac{1}{1+\exp(-x)}
\end{aligned}
\]</span></p>
<p>Here</p>
<ul>
<li class="fragment"><span class="math inline">\(\bbeta\)</span> learned using quasi maximum likelihood</li>
<li class="fragment">Default value for <span class="math inline">\(\theta\)</span> is 0.5</li>
</ul>
</section>
<section id="examples-of-linear-classifiers-svm" class="slide level4">
<h4>Examples of Linear Classifiers: SVM</h4>
<p>Support vector machines (<code>-1</code>, <code>+1</code> labels) <span class="math display">\[
h(\bx)  = \mathrm{sign}\curl{  \varphi(\bx)'\bbeta - \theta  }
\]</span> More on SVMs later</p>
<p>Here</p>
<ul>
<li class="fragment"><span class="math inline">\(\bbeta\)</span> chosen to maximize the separating <em>margin</em> between classes (with some tolerance of errors)</li>
<li class="fragment">Default value of <span class="math inline">\(\theta\)</span> is 0</li>
</ul>
</section>
<section id="nonlinear-classifiers" class="slide level4">
<h4>Nonlinear Classifiers</h4>
<p>Many classifiers cannot be represented in form (<a href="#/eq-linear-classifier" class="quarto-xref">1</a>)</p>
<div class="fragment">
<p><br></p>
<p>The most relevant examples:</p>
<ul>
<li class="fragment">Decision trees and their ensembles (random forests and gradient boosted machines)</li>
<li class="fragment">Neural networks with nonlinear activation functions</li>
<li class="fragment">Nearest neigbhors</li>
</ul>
</div>
</section>
<section id="logistic-regression" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Logistic Regression</h3>

</section>
<section id="objective-function" class="slide level4">
<h4>Objective Function</h4>
<p>Classifier <span class="math display">\[ \small
h(\bx) = \I\curl{  \Lambda( \varphi(\bx)'\bbeta  ) \geq \theta  }
\]</span></p>
<p><span class="math inline">\(\bbeta\)</span> chosen by maximizing (penalized) quasi-log likelihood: <span class="math display">\[ \tiny
\hat{\bbeta}^{QML} = \argmax_{\bb} \sum_{i=1}^N\left[Y_i  \log(\Lambda( \bX_i'\bbeta  )) + (1-Y_i) \log\left( 1 - \Lambda( \bX_i'\bbeta  ) \right)    \right] + \alpha \Pcal(\bbeta)
\]</span> Recall interpretation: model learning to predict probabilities of <span class="math inline">\(Y=1\)</span> with <span class="math inline">\(\Lambda(\bX'\beta)\)</span></p>
</section>
<section id="logistic-regression-in-scikit-learn" class="slide level4">
<h4>Logistic Regression in <code>scikit-learn</code></h4>
<p>Two main ways:</p>
<ul>
<li class="fragment"><code>LogisticRegression</code></li>
<li class="fragment"><code>SGDClassifier</code> with <code>loss=log_loss</code></li>
</ul>
<div class="fragment">
<p>Main difference between the two — optimization method</p>
<ul>
<li class="fragment"><code>LogisticRegression</code> uses whole sample simultaneously (and also Hessian information)</li>
<li class="fragment"><code>SGDClassifier</code> uses <span class="highlight">stochastic gradient descent</span> — updates parameter guess using gradient evaluated a single example at a time</li>
</ul>
<div class="footer">
<p>Most ML books discuss SGD. For example, see ch.&nbsp;14 in <span class="citation" data-cites="Shalev-Shwartz2014UnderstandingMachineLearning">Shalev-Shwartz and Ben-David (<a href="#/references-1" role="doc-biblioref" onclick="">2014</a>)</span></p>
</div>
</div>
</section>
<section id="illustration-logistic-regression" class="slide level4">
<h4>Illustration: Logistic Regression</h4>
<p>For example:</p>
<div id="c7dd0375" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a></a>logit <span class="op">=</span> Pipeline(</span>
<span id="cb11-2"><a></a>  [</span>
<span id="cb11-3"><a></a>    (<span class="st">'scale'</span>, StandardScaler()),</span>
<span id="cb11-4"><a></a>    (<span class="st">'logit'</span>, LogisticRegression(penalty<span class="op">=</span><span class="va">None</span>))</span>
<span id="cb11-5"><a></a>  ]</span>
<span id="cb11-6"><a></a>)</span>
<span id="cb11-7"><a></a></span>
<span id="cb11-8"><a></a>logit.fit(X_train, y_train_0)</span>
<span id="cb11-9"><a></a>logit.predict([X_train[<span class="dv">0</span>, :]]) <span class="op">==</span> y_train_0[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>array([ True])</code></pre>
</div>
</div>
<ul>
<li class="fragment">Managed to predict the first training sample right</li>
<li class="fragment">But how good is it overall?</li>
</ul>
</section>

<section id="support-vector-machines" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Support Vector Machines</h3>

</section>
<section id="linear-svm-classifier" class="slide level4">
<h4>Linear SVM: Classifier</h4>
<p>Consider first linear case:</p>
<ul>
<li class="fragment">Some feature <span class="math inline">\(\bX\)</span></li>
<li class="fragment">Binary label <span class="math inline">\(Y\in \curl{-1, 1}\)</span></li>
</ul>
<div class="fragment">
<p>Classifier takes form <span class="math display">\[
h(\bx) = \mathrm{sign}\curl{ \bx'\bbeta + c \geq 0  }
\]</span> Decision depends on which side of the hyperplane <span class="math inline">\(\bx'\bbeta+c=0\)</span> the new point falls</p>
</div>
</section>
<section id="illustration-separable-classes" class="slide level4">
<h4>Illustration: Separable Classes</h4>
<div class="columns">
<div class="column" style="width:65%;">
<p><img data-src="../..\images/pred/svm-1.png"></p>
</div><div class="column" style="width:35%;">
<ul>
<li class="fragment">Suppose classes can be separated linearly</li>
<li class="fragment">Then usually many possible separating hyperplanes (different <span class="math inline">\(\bbeta\)</span>)</li>
</ul>
</div></div>
<div class="fragment">
<p>“Safest” classifier — one that separates classes with <span class="highlight">maximum margin</span> (right plot)</p>
<div class="footer">
<p>Illustration: figure 5.1 in <span class="citation" data-cites="Mohri2018FoundationsMachineLearning">Mohri, Rostamizadeh, and Talwalkar (<a href="#/references-1" role="doc-biblioref" onclick="">2018</a>)</span></p>
</div>
</div>
</section>
<section id="nonseparable-case" class="slide level4">
<h4>Nonseparable Case</h4>
<div class="columns">
<div class="column" style="width:60%;">
<p><img data-src="../..\images/pred/svm-2.png"></p>
</div><div class="column" style="width:40%;">
<p>If classes not separable</p>
<ul>
<li class="fragment">Accept that some errors will happen, try to minimize them</li>
<li class="fragment">Try to maximize the margin between the separated points</li>
</ul>
</div></div>
</section>
<section id="linear-svm-learning-problem" class="slide level4">
<h4>Linear SVM: Learning Problem</h4>
<p><span class="math display">\[
\begin{aligned}
&amp; \min_{\bbeta, c, \bxi} \dfrac{1}{2} \norm{\bbeta}_2^2 + C\sum_{i=1}^m \xi_i^p, \\
&amp; \text{s.t.} \forall i: Y_i(\bbeta'\bX_i+ c) \geq 1-\xi_i, \quad \xi_i\geq 0.
\end{aligned}
\]</span></p>
<p>Has to balance two things:</p>
<ul>
<li class="fragment">Maximizing margin (=minimizing norm of <span class="math inline">\(\bbeta\)</span>)</li>
<li class="fragment">Not making too many errors <span class="math inline">\(\xi_i\)</span></li>
<li class="fragment"><span class="math inline">\(C\)</span> and <span class="math inline">\(p\)</span> are tuning parameters</li>
</ul>
<div class="footer">
<p>For full mathematical details, see chapter 5 in <span class="citation" data-cites="Mohri2018FoundationsMachineLearning">Mohri, Rostamizadeh, and Talwalkar (<a href="#/references-1" role="doc-biblioref" onclick="">2018</a>)</span></p>
</div>
</section>
<section id="linear-svm-learning-problem-discussion" class="slide level4">
<h4>Linear SVM: Learning Problem Discussion</h4>
<ul>
<li class="fragment">Typical values for <span class="math inline">\(p\)</span> are <span class="math inline">\(p=1\)</span> and <span class="math inline">\(p=2\)</span></li>
<li class="fragment">There are other expressions for objective. E.g. with <span class="math inline">\(p=1\)</span> can express as penalized ERM with <span class="highlight">hinge loss</span> <span class="math display">\[ \small
\begin{aligned}
\argmin_{\bbeta, c} &amp; \hspace{3mm} C' \norm{\bbeta}_2^2+\frac{1}{m}\sum_{i=1}^m l_h(1-Y_i(\bbeta'\bX_i-c))\\
l_h(x) &amp; = \max\curl{0, 1-x}
\end{aligned}
\]</span></li>
</ul>
<div class="callout callout-note no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>The SVM name comes from the fact that solution is determined by only certain specific observations called <span class="highlight">support vectors </span> (on dashed lines in figure before)</p>
</div>
</div>
</div>
<div class="footer">

</div>
</section>
<section id="nonlinear-svms" class="slide level4">
<h4>Nonlinear SVMs</h4>
<div class="columns">
<div class="column" style="width:80%;">
<p><img data-src="../..\images/pred/svm-3.png"></p>
</div><div class="column" style="width:20%;">
<p>One can allow classifier to be nonlinear in <span class="math inline">\(\bX\)</span></p>
</div></div>
<p><span class="math display">\[
h(\bx) = \mathrm{sign}\curl{ \varphi(\bx)'\bbeta + c \geq 0  }
\]</span></p>
</section>
<section id="kernel-trick" class="slide level4">
<h4>Kernel Trick</h4>
<div class="rounded-box">
<p>SVMs allow easily working with very high-dimensional <span class="math inline">\(\varphi(\bx)\)</span></p>
</div>
<p>Key reason — property called the <span class="highlight">kernel trick</span>. Essentially:</p>
<ul>
<li class="fragment">You often don’t need to explicitly compute each <span class="math inline">\(\varphi(\bx)\)</span> (may be slow if <span class="math inline">\(\varphi\)</span> has large dimension)</li>
<li class="fragment">Sufficient to find a function called <span class="highlight">kernel</span> that implicitly represents the geometry of the new space</li>
</ul>
<div class="callout callout-note no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Popular kernels include polynomials (finite-dimensional) and radial basis functions (infinite-dimensional)</p>
</div>
</div>
</div>
<div class="footer">
<p>See chapter 16 in <span class="citation" data-cites="Shalev-Shwartz2014UnderstandingMachineLearning">Shalev-Shwartz and Ben-David (<a href="#/references-1" role="doc-biblioref" onclick="">2014</a>)</span></p>
</div>
</section>
<section id="advantages-and-disadvantages-of-svms" class="slide level4">
<h4>Advantages and Disadvantages of SVMs</h4>
<p>Advantages:</p>
<ul>
<li class="fragment">Can work with potentially infinite-dimensional features
<ul>
<li class="fragment">Theoretically because SVMs performance depends only on margin, but not dimension</li>
<li class="fragment">Practically thanks to the kernel trick</li>
</ul></li>
<li class="fragment">More resistant to overfitting</li>
<li class="fragment">Very quick prediction</li>
</ul>
<div class="fragment">
<p>The main disadvantage: <span class="highlight">scale poorly</span> in terms of sample size (sweet spot seems to be <span class="math inline">\(&lt;100\)</span>k examples)</p>
<div class="footer">

</div>
</div>
</section>
<section id="svms-in-scikit-learn" class="slide level4">
<h4>SVMs in <code>scikit-learn</code></h4>
<p>Linear SVMs implemented in several classes in <code>scikit-learn</code>:</p>
<ul>
<li class="fragment"><code>SGDClassifier</code> with loss <code>loss='hinge'</code> (or <code>squared_hinge</code>, or <code>perceptron</code>)</li>
<li class="fragment"><code>LinearSVC</code>: faster implementation only for linear SVMs</li>
<li class="fragment"><code>SVC</code>: supports kernel trick and various standard kernels, but slower</li>
</ul>
<div class="callout callout-note no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>“Linear SVM” means that if you want to use <span class="math inline">\(\varphi(\bx)\)</span>, you have to explicitly compute those yourself as part of data preparation</p>
</div>
</div>
</div>
</section>
<section id="fitting-an-svm" class="slide level4">
<h4>Fitting an SVM</h4>
<p>Fitting as easy as always:</p>
<div id="c124ff0a" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a></a>svm <span class="op">=</span> Pipeline(</span>
<span id="cb13-2"><a></a>  [</span>
<span id="cb13-3"><a></a>    (<span class="st">'scale'</span>, StandardScaler()),</span>
<span id="cb13-4"><a></a>    (<span class="st">'svm'</span>, SGDClassifier(random_state<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb13-5"><a></a>  ]</span>
<span id="cb13-6"><a></a>)</span>
<span id="cb13-7"><a></a></span>
<span id="cb13-8"><a></a>svm.fit(X_train, y_train_0)</span>
<span id="cb13-9"><a></a>svm.predict([X_train[<span class="dv">0</span>, :]]) <span class="op">==</span> y_train_0[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>array([ True])</code></pre>
</div>
</div>
</section>

<section id="classification-trees-and-forests" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Classification Trees and Forests</h3>

</section>
<section id="fitting-a-classification-forest" class="slide level4">
<h4>Fitting a Classification Forest</h4>
<p>To complete the picture, can add a tree-based classifier — <code>RandomForestClassifier</code>. RF classifiers very similar to RF regressors (last lecture)</p>
<div id="cb6702ee" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a></a>rf <span class="op">=</span> Pipeline(</span>
<span id="cb15-2"><a></a>  [</span>
<span id="cb15-3"><a></a>    (<span class="st">'scale'</span>, StandardScaler()),</span>
<span id="cb15-4"><a></a>    (<span class="st">'forest'</span>, RandomForestClassifier(random_state<span class="op">=</span><span class="dv">1</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>))</span>
<span id="cb15-5"><a></a>  ]</span>
<span id="cb15-6"><a></a>)</span>
<span id="cb15-7"><a></a></span>
<span id="cb15-8"><a></a>rf.fit(X_train, y_train_0)</span>
<span id="cb15-9"><a></a>rf.predict([X_train[<span class="dv">0</span>, :]]) <span class="op">==</span> y_train_0[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>array([ True])</code></pre>
</div>
</div>
</section>
</section>
<section>
<section id="evaluating-classifiers" class="title-slide slide level2 center" data-background="#00100F">
<h2>Evaluating Classifiers</h2>

</section>
<section id="scalar-metrics" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Scalar Metrics</h3>

</section>
<section id="evaluating-binary-classifiers" class="slide level4">
<h4>Evaluating Binary Classifiers</h4>
<p>How does one evaluate a classifier?</p>
<p>Several metrics:</p>
<ul>
<li class="fragment">Accuracy</li>
<li class="fragment">Confusion matrix</li>
<li class="fragment">Precision and recall, <span class="math inline">\(F_{\beta}\)</span> scores</li>
<li class="fragment">The ROC curve and area under the curve (AUC)</li>
</ul>
</section>
<section id="accuracy" class="slide level4">
<h4>Accuracy</h4>
<p>First metric — accuracy</p>
<ul>
<li class="fragment">Accuracy — proportion of correctly classified new points</li>
<li class="fragment">Can again evaluate with CV using <code>cross_val_score</code></li>
</ul>
<div id="ae450a4c" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a></a>logit_accuracy <span class="op">=</span> cross_val_score(</span>
<span id="cb17-2"><a></a>    logit, </span>
<span id="cb17-3"><a></a>    X_train, </span>
<span id="cb17-4"><a></a>    y_train_0,</span>
<span id="cb17-5"><a></a>    cv<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb17-6"><a></a>    n_jobs<span class="op">=-</span><span class="dv">1</span>,</span>
<span id="cb17-7"><a></a>    scoring<span class="op">=</span><span class="st">"accuracy"</span></span>
<span id="cb17-8"><a></a>)</span>
<span id="cb17-9"><a></a>logit_accuracy.mean().<span class="bu">round</span>(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>np.float64(0.9896)</code></pre>
</div>
</div>
</section>
<section id="benchmark" class="slide level4">
<h4>Benchmark</h4>
<p>We have 98.65% accuracy. Is that good?</p>
<div class="rounded-box">
<p>Important to always have a basic benchmark</p>
</div>
<div class="fragment">
<ul>
<li class="fragment">Can use <code>DummyClassifier</code> from <code>sklearn.dummy</code> as benchmark</li>
<li class="fragment">Benchmark strategy: predicting the most popular class (“not 0”)</li>
</ul>
<div id="e8b7058f" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Accuracy of dummy classifier</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a></a>dummy_clf <span class="op">=</span> DummyClassifier()</span>
<span id="cb19-2"><a></a>dummy_clf.fit(X_train, y_train_0)</span>
<span id="cb19-3"><a></a>cross_val_score(dummy_clf, X_train, y_train_0, cv<span class="op">=</span><span class="dv">5</span>, scoring<span class="op">=</span><span class="st">"accuracy"</span>).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>np.float64(0.9012833333333333)</code></pre>
</div>
</div>
<div class="footer">

</div>
</div>
</section>
<section id="confusion-matrix-intro" class="slide level4">
<h4>Confusion Matrix: Intro</h4>
<ul>
<li class="fragment">Accuracy combines all errors into one number</li>
<li class="fragment">But maybe want to decompose more carefully</li>
</ul>
<div class="fragment">
<p>Some terminology:</p>
<ol type="1">
<li class="fragment">Correct predictions: are true positive (TP) and true negative (TN)</li>
<li class="fragment">Incorrect predictions are false positive (FP, type I error) and false negative (FN, type II error)</li>
</ol>
</div>
</section>
<section id="confusion-matrix-enumerating-tp-tn-fp-fn" class="slide level4">
<h4>Confusion Matrix: Enumerating TP, TN, FP, FN</h4>
<ul>
<li class="fragment"><span class="math inline">\((i, j)\)</span>th element — number of observations of class <span class="math inline">\(i\)</span> labeled as class <span class="math inline">\(j\)</span></li>
<li class="fragment">Correct way to evaluate — using cross-validation (to get more accurate picture of classifier’s performance)</li>
</ul>
<div id="c9b8bb19" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a></a>y_train_pred_logit <span class="op">=</span> cross_val_predict(logit, X_train, y_train_0, cv<span class="op">=</span><span class="dv">5</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb21-2"><a></a></span>
<span id="cb21-3"><a></a><span class="co"># Compute the confusion matrix</span></span>
<span id="cb21-4"><a></a>confusion_matrix(</span>
<span id="cb21-5"><a></a>    y_train_0, </span>
<span id="cb21-6"><a></a>    y_train_pred_logit,  </span>
<span id="cb21-7"><a></a>).<span class="bu">round</span>(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>array([[53763,   314],
       [  307,  5616]])</code></pre>
</div>
</div>
<div class="footer">
<p>Remember to keep track of what the classes are: class 0 is <code>not 0</code>, class 1 is <code>'0'</code></p>
</div>
</section>
<section id="confusion-matrix-normalizing-by-rows-or-columns" class="slide level4">
<h4>Confusion Matrix: Normalizing By Rows or Columns</h4>
<p>If we row-normalize confusion matrix, second row — <span class="highlight">proportions</span> of 0 identified as “not 0” and 0</p>
<div id="f9df777a" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a></a><span class="co"># Compute the confusion matrix</span></span>
<span id="cb23-2"><a></a>confusion_matrix(</span>
<span id="cb23-3"><a></a>    y_train_0, </span>
<span id="cb23-4"><a></a>    y_train_pred_logit, </span>
<span id="cb23-5"><a></a>    normalize<span class="op">=</span><span class="st">'true'</span>,</span>
<span id="cb23-6"><a></a>).<span class="bu">round</span>(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>array([[0.9942, 0.0058],
       [0.0518, 0.9482]])</code></pre>
</div>
</div>
<p>Can see: logit very good at detecting not 0s, but marks around 5.1% percents of 0s as not 0s</p>
<div class="footer">

</div>
</section>
<section id="precision-and-recall-definitions" class="slide level4">
<h4>Precision and Recall: Definitions</h4>
<p>Two important metrics related to confusion matrix <span class="math display">\[ \small
\begin{aligned}
\text{Precision} &amp; = \dfrac{TP}{TP+FP}, \\
\text{Recall} &amp; = \dfrac{TP}{TP+FN}
\end{aligned}
\]</span></p>
<ul>
<li class="fragment">Precision: how often the <code>'0'</code> label is right</li>
<li class="fragment">Recall: how many of the <code>'0'</code>s are detected</li>
</ul>
</section>
<section id="precision-and-recall-computing" class="slide level4">
<h4>Precision and Recall: Computing</h4>
<ul>
<li class="fragment">Can compute precision and recall from normalized confusion matrix (by column and by row, respectively. Think how)</li>
<li class="fragment">Or use special functions from <code>sklearn.metrics</code>:</li>
</ul>
<div id="95d99d47" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a></a><span class="bu">print</span>(<span class="ss">f"Precision: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(precision_score(y_train_0, y_train_pred_logit), <span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb25-2"><a></a><span class="bu">print</span>(<span class="ss">f"Recall: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(recall_score(y_train_0, y_train_pred_logit), <span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Precision: 0.947
Recall: 0.948</code></pre>
</div>
</div>
<p>Very close in terms of both</p>
</section>
<section id="f-scores" class="slide level4">
<h4><span class="math inline">\(F\)</span>-Scores</h4>
<p>Precision and recall can be combined into a single metric using <span class="math inline">\(F_{\beta}\)</span> score</p>
<p>Most famous — the <span class="math inline">\(F_1\)</span> score: <span class="math display">\[
F_1 = \dfrac{  2 }{
    \frac{1}{\text{Recall}} + \frac{1}{\text{Precision}}
   }
\]</span></p>
<p>We can compute it using <code>f1_score()</code> from <code>sklearn.metrics</code>:</p>
<div id="f36e261a" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a></a><span class="bu">print</span>(<span class="ss">f"F1: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(f1_score(y_train_0, y_train_pred_logit), <span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>F1: 0.948</code></pre>
</div>
</div>
</section>
<section id="comparing-different-classifiers" class="slide level4">
<h4>Comparing Different Classifiers</h4>
<ul>
<li class="fragment">So now we can compare the different classifiers we trained on several metrics</li>
<li class="fragment">Compare based on <span class="math inline">\(F_1\)</span>:</li>
</ul>
<div id="68e58144" class="cell" data-execution_count="19">
<div class="cell-output cell-output-stdout">
<pre><code>Logit: 0.948
SVM: 0.944
RF: 0.971</code></pre>
</div>
</div>
<p>Random forests come out ahead!</p>
</section>

<section id="curves" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Curves</h3>

</section>
<section id="regarding-decision-thresholds" class="slide level4">
<h4>Regarding Decision Thresholds</h4>
<p>Go back to logit classifier: <span class="math display">\[
h(\bx) = \I\curl{  \Lambda( \varphi(\bx)'\bbeta  ) \geq \theta  }
\]</span></p>
<ul>
<li class="fragment">By default <span class="math inline">\(\theta = 0.5\)</span> — label observation as 1 if predicted probability of 1 is higher than of 0</li>
<li class="fragment">But can change <span class="math inline">\(\theta\)</span>. E.g. lowering <span class="math inline">\(\theta\)</span>:
<ul>
<li class="fragment">More true positives</li>
<li class="fragment">More false positives</li>
</ul></li>
</ul>
</section>
<section id="roc-curve" class="slide level4">
<h4>ROC Curve</h4>
<div class="rounded-box">
<p>The <span class="highlight">ROC</span> (receiver operator characteristic) <span class="highlight">curve</span> shows the relationship true and false positives rates (TPR vs.&nbsp;FPR)</p>
</div>
<ul>
<li class="fragment">Computed by changing <span class="math inline">\(\theta\)</span> (between 0 and 1 for logit)</li>
<li class="fragment">In practice:
<ol type="1">
<li class="fragment">Compute the <span class="highlight">scores</span> <span class="math inline">\(\Lambda(\bX_i'\hat{\bbeta})\)</span> for each observation<br>
</li>
<li class="fragment">For each <span class="math inline">\(\theta\)</span>, compute which observations labeled as positive or negative by comparing <span class="math inline">\(\Lambda(\bX_i'\hat{\bbeta})\)</span> and <span class="math inline">\(\theta\)</span></li>
</ol></li>
</ul>
</section>
<section id="roc-curve-in-practice" class="slide level4">
<h4>ROC Curve in Practice</h4>
<p>In <code>scikit-learn</code> can use <code>cross_val_predict()</code> for scores and <code>roc_curve</code> for ROC curve</p>
<div id="fdecdda7" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a></a><span class="co"># Compute scores</span></span>
<span id="cb30-2"><a></a>y_scores_logit <span class="op">=</span> cross_val_predict(</span>
<span id="cb30-3"><a></a>    logit, </span>
<span id="cb30-4"><a></a>    X_train, </span>
<span id="cb30-5"><a></a>    y_train_0,</span>
<span id="cb30-6"><a></a>    cv<span class="op">=</span><span class="dv">5</span>, </span>
<span id="cb30-7"><a></a>    n_jobs<span class="op">=-</span><span class="dv">1</span>, </span>
<span id="cb30-8"><a></a>    method<span class="op">=</span><span class="st">"predict_proba"</span>,  <span class="co"># Which method to call</span></span>
<span id="cb30-9"><a></a>)  </span>
<span id="cb30-10"><a></a>y_scores_logit <span class="op">=</span> y_scores_logit[:, <span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb30-11"><a></a><span class="co"># Compute the ROC curve</span></span>
<span id="cb30-12"><a></a>fpr_logit, tpr_logit, thresholds <span class="op">=</span> roc_curve(y_train_0, y_scores_logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="roc-curve-for-logit" class="slide level4">
<h4>ROC Curve for Logit</h4>
<div id="0f357d60" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="classification_files/figure-revealjs/cell-22-output-1.png" width="1120" height="560"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="roc-curve-discussion" class="slide level4">
<h4>ROC Curve: Discussion</h4>
<ul>
<li class="fragment">Ideal classifier: FPR = 0, TPR = 1 (upper left corner)</li>
<li class="fragment">Better classifiers: ROC curve close to the upper left corner</li>
<li class="fragment">Can compute for any classifier with tunable <span class="math inline">\(\theta\)</span>
<ul>
<li class="fragment">Including random forest and SVM</li>
<li class="fragment">Not for a single decision tree</li>
</ul></li>
</ul>
</section>
<section id="roc-curves-for-all-classifiers" class="slide level4">
<h4>ROC Curves for All Classifiers</h4>
<div id="33693586" class="cell" data-execution_count="22">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="classification_files/figure-revealjs/cell-23-output-1.png" width="1120" height="560"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="auc" class="slide level4">
<h4>AUC</h4>
<div class="rounded-box">
<p><span class="highlight">Area under curve</span> (AUC) is the area under the ROC curve</p>
</div>
<ul>
<li class="fragment">Bigger AUC is better</li>
<li class="fragment">Ideal classifiers: AUC = 1</li>
<li class="fragment">Compute with <code>roc_auc_score()</code>:</li>
</ul>
<div id="dad79ffc" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a></a><span class="bu">print</span>(<span class="ss">f"Logit AUC: </span><span class="sc">{</span>roc_auc_score(y_train_0, y_scores_logit)<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb31-2"><a></a><span class="bu">print</span>(<span class="ss">f"SVM AUC: </span><span class="sc">{</span>roc_auc_score(y_train_0, y_scores_svm)<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb31-3"><a></a><span class="bu">print</span>(<span class="ss">f"RF AUC: </span><span class="sc">{</span>roc_auc_score(y_train_0, y_scores_rf)<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logit AUC: 0.996
SVM AUC: 0.997
RF AUC: 0.999</code></pre>
</div>
</div>
</section>
<section id="precision-recall-curve" class="slide level4">
<h4>Precision-Recall Curve</h4>
<ul>
<li class="fragment">ROC curves compare FPR and TPR (recall)</li>
<li class="fragment">Another trade-off — between recall/TPR and precision</li>
</ul>
<div class="fragment">
<div class="rounded-box">
<p>The <span class="highlight">precision-recall</span> curves measure the trade-off between between precision and recall</p>
</div>
<p><br></p>
<p>Compute with <code>precision_recall_curve()</code> from <code>sklearn.metrics</code>:</p>
<div id="7cdd21d8" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a></a>precisions_logit, recalls_logit, thresholds <span class="op">=</span> <span class="op">\</span></span>
<span id="cb33-2"><a></a>  precision_recall_curve(y_train_0, y_scores_logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="precision-recall-curve-for-logit" class="slide level4">
<h4>Precision-Recall Curve for Logit</h4>
<div id="29fe4c24" class="cell" data-execution_count="25">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="classification_files/figure-revealjs/cell-26-output-1.png" width="1102" height="560"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="precison-recall-curve-discussion" class="slide level4">
<h4>Precison-Recall Curve: Discussion</h4>
<ul>
<li class="fragment">Curve shows trade-off for most of <span class="math inline">\(\theta\)</span></li>
<li class="fragment">For <span class="math inline">\(\theta\uparrow 1\)</span> both recall and precision eventually fall
<ul>
<li class="fragment">Reason: <span class="math inline">\(\Lambda \in (0, 1)\)</span> — eventually no observation gets positive label</li>
<li class="fragment">Precision becomes 0/0</li>
<li class="fragment"><code>scikit-learn</code> evaluates that as 0 precision</li>
</ul></li>
</ul>
</section>
<section id="conclusion-metrics" class="slide level4">
<h4>Conclusion: Metrics</h4>
<p>Dicussed many metrics for binary classifiers</p>
<ul>
<li class="fragment">Which one matters depends on contexts</li>
<li class="fragment">Sometimes want more recall or precision
<ul>
<li class="fragment">Recall: preventing crime (catching all criminals)</li>
<li class="fragment">Precision: detecting spam (want to be certain of spam labels)</li>
</ul></li>
<li class="fragment">Some classifiers can be tuned on decision threshold</li>
</ul>
</section>
</section>
<section>
<section id="basics-of-multiclass-classification" class="title-slide slide level2 center" data-background="#00100F">
<h2>Basics of Multiclass Classification</h2>

</section>
<section id="multiclass-classification-algorithms" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Multiclass Classification Algorithms</h3>

</section>
<section id="setting-and-example" class="slide level4">
<h4>Setting and Example</h4>
<p>In a (single-output) multiclass setting <span class="math inline">\(Y\)</span> can belong to one of <span class="math inline">\(k\)</span> classes</p>
<div class="fragment">
<p><br></p>
<p>Example based on MNIST data</p>
<div class="rounded-box">
<p>Detect which of <code>'0'</code>, <code>'1'</code>, …, <code>'9'</code> a given collection of pixels represents</p>
</div>
</div>
</section>
<section id="classification-strategies" class="slide level4">
<h4>Classification Strategies</h4>
<ul>
<li class="fragment">Use classifier that can handle multiple classes <span class="highlight">directly</span></li>
<li class="fragment">Use several binary clssifiers:
<ul>
<li class="fragment"><span class="highlight">One-versus-all</span>: for each class <span class="math inline">\(j\)</span>, train classifier for the problem <span class="math inline">\(Y=j\)</span> vs.&nbsp;<span class="math inline">\(Y\neq j\)</span>. Predict class <span class="math inline">\(k\)</span> with maximum “confidence” that <span class="math inline">\(Y=k\)</span></li>
<li class="fragment"><span class="highlight">One-versus-one</span>: train a binary classifier for each pair of classes. Predict based on majority rule</li>
</ul></li>
</ul>
<div class="footer">

</div>
</section>
<section id="multinomial-logit-direct" class="slide level4">
<h4>Multinomial Logit (Direct)</h4>
<p>Suppose that classes are labeled with <span class="math inline">\(j=1, \dots, k\)</span></p>
<p>Multinomial logistic classifiers <span class="math display">\[
h(\bx) = \argmax_{j=1, \dots, k} \curl{ \dfrac{ \exp(\varphi(\bx)'\bbeta_j) }{ \sum_{l=1}^k \exp(\varphi(\bx)'\bbeta_l)  }  }
\]</span></p>
<ul>
<li class="fragment">Predicts probability for each class</li>
<li class="fragment">Selects class with highest predicted probability</li>
</ul>
</section>
<section id="multinomial-logit-in-scikit-learn" class="slide level4">
<h4>Multinomial Logit in <code>scikit-learn</code></h4>
<p><code>LogisticRegression</code> in <code>scikit-learn</code> automatically is multi-class by default. Trained the same way as before:</p>
<div id="8b589949" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a></a>logit <span class="op">=</span> Pipeline(</span>
<span id="cb34-2"><a></a>  [</span>
<span id="cb34-3"><a></a>    (<span class="st">'scale'</span>, StandardScaler()),</span>
<span id="cb34-4"><a></a>    (<span class="st">'logit'</span>, LogisticRegression(penalty<span class="op">=</span><span class="va">None</span>, max_iter<span class="op">=</span><span class="dv">1000</span>))</span>
<span id="cb34-5"><a></a>  ]</span>
<span id="cb34-6"><a></a>)</span>
<span id="cb34-7"><a></a></span>
<span id="cb34-8"><a></a>logit.fit(X_train, y_train)    <span class="co"># Use the full labels</span></span>
<span id="cb34-9"><a></a>logit.predict([X_train[<span class="dv">0</span>, :]]) <span class="op">==</span> y_train[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>array([ True])</code></pre>
</div>
</div>
<p>Predicts probabilities of each class:</p>
<div id="2cb53309" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a></a>logit.predict_proba([X_train[<span class="dv">0</span>, :]]).<span class="bu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>array([[0.004, 0.   , 0.   , 0.188, 0.   , 0.808, 0.   , 0.   , 0.   ,
        0.   ]])</code></pre>
</div>
</div>
<div class="footer">

</div>
</section>
<section id="decision-trees-and-random-forests" class="slide level4">
<h4>Decision Trees and Random Forests</h4>
<p>Decision trees and everything based on them can also directly learn multiple labels</p>
<div id="f5339c89" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a></a>rf <span class="op">=</span> Pipeline(</span>
<span id="cb38-2"><a></a>  [</span>
<span id="cb38-3"><a></a>    (<span class="st">'scale'</span>, StandardScaler()),</span>
<span id="cb38-4"><a></a>    (<span class="st">'forest'</span>, RandomForestClassifier(random_state<span class="op">=</span><span class="dv">1</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>))</span>
<span id="cb38-5"><a></a>  ]</span>
<span id="cb38-6"><a></a>)</span>
<span id="cb38-7"><a></a></span>
<span id="cb38-8"><a></a>rf.fit(X_train, y_train)</span>
<span id="cb38-9"><a></a>rf.predict_proba([X[<span class="dv">0</span>, :]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>array([[0.  , 0.  , 0.01, 0.09, 0.  , 0.83, 0.  , 0.02, 0.02, 0.03]])</code></pre>
</div>
</div>
</section>
<section id="svms-binary-collection" class="slide level4">
<h4>SVMs (Binary Collection)</h4>
<p>SVMs are binary-only: have to use OvO or OvA. <code>scikit-learn</code> handles that automatically</p>
<div id="17ed62a4" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a></a>svm <span class="op">=</span> Pipeline(</span>
<span id="cb40-2"><a></a>  [</span>
<span id="cb40-3"><a></a>    (<span class="st">'scale'</span>, StandardScaler()),</span>
<span id="cb40-4"><a></a>    (<span class="st">'svm'</span>, SGDClassifier(random_state<span class="op">=</span><span class="dv">1</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>))</span>
<span id="cb40-5"><a></a>  ]</span>
<span id="cb40-6"><a></a>)</span>
<span id="cb40-7"><a></a></span>
<span id="cb40-8"><a></a>svm.fit(X_train, y_train)</span>
<span id="cb40-9"><a></a><span class="bu">print</span>(svm.decision_function([X_train[<span class="dv">0</span>, :]]).<span class="bu">round</span>(<span class="dv">2</span>))</span>
<span id="cb40-10"><a></a><span class="bu">print</span>(svm.classes_)</span>
<span id="cb40-11"><a></a><span class="bu">print</span>(svm.predict([X_train[<span class="dv">0</span>, :]]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[-1078.89 -1077.14  -438.67   -14.08 -1669.25    -9.65 -1726.31  -668.26
   -102.42  -639.22]]
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
['5']</code></pre>
</div>
</div>
<div class="footer">
<p>You can set the strategy directly using special <code>OneVsOneClassifier</code> and <code>OneVsRestClassifier</code> classes</p>
</div>
</section>

<section id="evaluating-multiclass-classifiers" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Evaluating Multiclass Classifiers</h3>

</section>
<section id="evaluating-multiclass-classifiers-1" class="slide level4">
<h4>Evaluating Multiclass Classifiers</h4>
<p>Key basic metrics:</p>
<ul>
<li class="fragment">Accuracy</li>
<li class="fragment">Confusion matrices</li>
</ul>
<div class="fragment">
<p>Can also use pairwise precisions, recalls, ROC curves etc. These can be averaged or not</p>
</div>
</section>
<section id="accuracy-1" class="slide level4 scrollable">
<h4>Accuracy</h4>
<p>Accuracy: evaluate as before</p>
<div id="2034b760" class="cell" data-execution_count="30">
<details class="code-fold">
<summary>Computing accuracy of our classifiers</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a></a>logit_acc <span class="op">=</span>cross_val_score(</span>
<span id="cb42-2"><a></a>    logit,</span>
<span id="cb42-3"><a></a>    X_train,</span>
<span id="cb42-4"><a></a>    y_train,</span>
<span id="cb42-5"><a></a>    n_jobs<span class="op">=-</span><span class="dv">1</span>,</span>
<span id="cb42-6"><a></a>    scoring<span class="op">=</span><span class="st">"accuracy"</span>,</span>
<span id="cb42-7"><a></a>).mean()</span>
<span id="cb42-8"><a></a>rf_acc <span class="op">=</span> cross_val_score(</span>
<span id="cb42-9"><a></a>    rf,</span>
<span id="cb42-10"><a></a>    X_train,</span>
<span id="cb42-11"><a></a>    y_train,</span>
<span id="cb42-12"><a></a>    n_jobs<span class="op">=-</span><span class="dv">1</span>,</span>
<span id="cb42-13"><a></a>    scoring<span class="op">=</span><span class="st">"accuracy"</span>,</span>
<span id="cb42-14"><a></a>).mean() </span>
<span id="cb42-15"><a></a></span>
<span id="cb42-16"><a></a><span class="bu">print</span>(<span class="ss">f"Logit: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(logit_acc, <span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>) </span>
<span id="cb42-17"><a></a><span class="bu">print</span>(<span class="ss">f"RF: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(rf_acc, <span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Logit: 0.908
RF: 0.966</code></pre>
</div>
</div>
<ul>
<li class="fragment">Logit right about 90% of the time</li>
<li class="fragment">RF right around 96.6% of the time</li>
<li class="fragment">Both below the 98.5% human accuracy benchmark</li>
<li class="fragment">That threshold hard to break with “shallow” methods <span class="citation" data-cites="An2020EnsembleSimpleConvolutional">(<a href="#/references-1" role="doc-biblioref" onclick="">An et al. 2020</a>)</span>, but CNNs achieve &gt;99% accuracy</li>
</ul>
<div class="footer">

</div>
</section>
<section id="confusion-matrix-for-random-forest" class="slide level4">
<h4>Confusion Matrix for Random Forest</h4>
<ul>
<li class="fragment">Confusion matrices also computed as before</li>
<li class="fragment">With <span class="math inline">\(k\)</span> classes confsion matrices are <span class="math inline">\(k\times k\)</span></li>
</ul>
<div id="07c9f5e1" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a></a><span class="co"># Compute predictions</span></span>
<span id="cb44-2"><a></a>y_train_pred <span class="op">=</span> cross_val_predict(rf, X_train, y_train, cv<span class="op">=</span><span class="dv">5</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb44-3"><a></a><span class="co"># Build confusion matrix from predictions</span></span>
<span id="cb44-4"><a></a>confusion_matrix(</span>
<span id="cb44-5"><a></a>    y_train, </span>
<span id="cb44-6"><a></a>    y_train_pred,</span>
<span id="cb44-7"><a></a>    normalize<span class="op">=</span><span class="st">'true'</span>,</span>
<span id="cb44-8"><a></a>).<span class="bu">round</span>(<span class="dv">3</span>)[<span class="dv">0</span>:<span class="dv">4</span>, <span class="dv">0</span>:<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>array([[0.987, 0.   , 0.002, 0.   ],
       [0.   , 0.986, 0.006, 0.001],
       [0.005, 0.002, 0.967, 0.004],
       [0.001, 0.001, 0.014, 0.947]])</code></pre>
</div>
</div>
</section>
<section id="readable-matrices-with-confusionmatrixdisplay" class="slide level4">
<h4>Readable Matrices with <code>ConfusionMatrixDisplay</code></h4>
<div id="37738076" class="cell" data-execution_count="32">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="classification_files/figure-revealjs/cell-33-output-1.png" width="1176" height="547"></p>
</figure>
</div>
</div>
</div>
<div class="footer">
<p>Error matrix: proportion of errors. Helps to see which digits mistaken for which ones</p>
</div>
</section>
</section>
<section>
<section id="recap-and-conclusions" class="title-slide slide level2 center" data-background="#00100F">
<h2>Recap and Conclusions</h2>

</section>
<section id="lecture-recap" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Lecture Recap</h3>

</section>
<section id="recap" class="slide level4">
<h4>Recap</h4>
<p><br></p>
<p>In this lecture we</p>
<ol type="1">
<li class="fragment">Discussed basics of binary and multiclass classification</li>
<li class="fragment">Introduced several classification algorithms</li>
<li class="fragment">Talked about evaluating classifiers with a variety of metrics</li>
</ol>
</section>

<section id="block-conclusions" class="title-slide slide level3 center" data-background="#43464B" data-visibility="uncounted">
<h3>Block Conclusions</h3>

</section>
<section id="overal-concluding-thoughts" class="slide level4">
<h4>Overal Concluding Thoughts</h4>
<p>A look at machine learning, particularly supervised:</p>
<ul>
<li class="fragment">Key pieces of formalizing problems (risk, hypothesis classes)</li>
<li class="fragment">Motivation for acquiring specialized knowledge (no-free-lunch theorem)</li>
<li class="fragment">Some algorithms for
<ul>
<li class="fragment">Regression</li>
<li class="fragment">Classification</li>
</ul></li>
<li class="fragment">Validating and testing approaches</li>
</ul>
</section>
<section id="the-many-paths-forward" class="slide level4">
<h4>The Many Paths Forward</h4>
<ul>
<li class="fragment">Diving into theory (e.g.&nbsp;with <span class="citation" data-cites="Mohri2018FoundationsMachineLearning">Mohri, Rostamizadeh, and Talwalkar (<a href="#/references-1" role="doc-biblioref" onclick="">2018</a>)</span>)</li>
<li class="fragment">Unsupervised learning (see <span class="citation" data-cites="Hastie2009ElementsStatisticalLearning">Hastie, Tibshirani, and Friedman (<a href="#/references-1" role="doc-biblioref" onclick="">2009</a>)</span>)</li>
<li class="fragment">There are still more “shallow” learning algorithms, such as gradient boosting (see either of above books)</li>
<li class="fragment">Deep learning (see <span class="citation" data-cites="Bishop2024DeepLearningFoundations">Bishop and Bishop (<a href="#/references-1" role="doc-biblioref" onclick="">2024</a>)</span>)</li>
<li class="fragment">Field-specific applications (natural language processing, computer vision, recommenders, …)</li>
</ul>
<div class="footer">

</div>
</section>
<section id="references-1" class="slide level4 allowframebreaks smaller scrollable" data-visibility="uncounted">
<h4>References</h4>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-An2020EnsembleSimpleConvolutional" class="csl-entry" role="listitem">
An, Sanghyeon, Minjun Lee, Sanglee Park, Heerin Yang, and Jungmin So. 2020. <span>“An <span>Ensemble</span> of <span>Simple Convolutional Neural Network Models</span> for <span>MNIST Digit Recognition</span>.”</span> arXiv. <a href="https://doi.org/10.48550/arXiv.2008.10400">https://doi.org/10.48550/arXiv.2008.10400</a>.
</div>
<div id="ref-Bishop2024DeepLearningFoundations" class="csl-entry" role="listitem">
Bishop, Christopher M., and Hugh Bishop. 2024. <em>Deep <span>Learning</span>: <span>Foundations</span> and <span>Concepts</span></em>. Cham: Springer International Publishing. <a href="https://doi.org/10.1007/978-3-031-45468-4">https://doi.org/10.1007/978-3-031-45468-4</a>.
</div>
<div id="ref-Hastie2009ElementsStatisticalLearning" class="csl-entry" role="listitem">
Hastie, Trevor, Robert Tibshirani, and J. H. Friedman. 2009. <em>The <span>Elements</span> of <span>Statistical Learning</span>: <span>Data Mining</span>, <span>Inference</span>, and <span>Prediction</span></em>. 2nd ed. Springer <span>Series</span> in <span>Statistics</span>. New York, NY: Springer.
</div>
<div id="ref-James2023IntroductionStatisticalLearning" class="csl-entry" role="listitem">
James, Gareth, Daniela Witten, Trevor Hastie, Robert Tibshirani, and Jonathan E. Taylor. 2023. <em>An <span>Introduction</span> to <span>Statistical Learning</span>: <span>With Applications</span> in <span>Python</span></em>. Springer Texts in Statistics. Cham: Springer.
</div>
<div id="ref-Mohri2018FoundationsMachineLearning" class="csl-entry" role="listitem">
Mohri, Mehryar, Afshin Rostamizadeh, and Ameet Talwalkar. 2018. <em>Foundations of <span>Machine Learning</span></em>. The MIT Press. <a href="https://doi.org/10.5555/3360093">https://doi.org/10.5555/3360093</a>.
</div>
<div id="ref-Shalev-Shwartz2014UnderstandingMachineLearning" class="csl-entry" role="listitem">
Shalev-Shwartz, Shai, and Shai Ben-David. 2014. <em>Understanding <span>Machine Learning</span></em>. 1st ed. West Nyack: Cambridge University Press.
</div>
<div id="ref-Simard1992EfficientPatternRecognition" class="csl-entry" role="listitem">
Simard, Patrice, Yann Le Cun, and John Denker. 1992. <span>“Efficient <span>Pattern Recognition Using</span> a <span>New Transformation Distance</span>.”</span> In <em>Proceedings of the 6th <span>International Conference</span> on <span>Neural Information Processing Systems</span></em>, 50–58. <span>NIPS</span>’92. San Francisco, CA, USA: Morgan Kaufmann Publishers Inc.
</div>
</div>
<div class="footer">

</div>


<div class="reveal-header">
<div class="header-logo" data-footer-logo-link="https://vladislav-morozov.github.io/econometrics-2/">
<img data-src="">
</div>
<div class="sc-title">
<p> </p>
</div>
<div class="header-text">
<p> </p>
</div>
<div class="sb-title">
<p> </p>
</div>
</div>
</section>
</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../../themes/favicon.ico" class="slide-logo"></p>
<div class="footer footer-default">
<p>Classification</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'convex',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1150,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp("https:\/\/vladislav-morozov\.github\.io\/econometrics-2\/");
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>