---
title: "Statistical and Machine Learning"
subtitle: "Prediction and Learning Scenarios"
author: Vladislav Morozov  
format:
  revealjs:
    include-in-header: 
      text: |
        <meta name="description" content="  (lecture notes slides)."/>
    width: 1150
    slide-number: true
    sc-sb-title: true
    incremental: true   
    logo: ../../themes/favicon.ico
    footer: "Prediction: Introduction"
    footer-logo-link: "https://vladislav-morozov.github.io/econometrics-2/"
    theme: ../../themes/slides_theme.scss
    toc: TRUE
    toc-depth: 2
    toc-title: Contents
    transition: convex
    transition-speed: fast
slide-level: 4
title-slide-attributes:
    data-background-color: "#045D5D"
    data-footer: " "
filters:
  - reveal-header  
include-in-header: ../../themes/mathjax.html 
highlight-style: tango
open-graph:
    description: " (lecture notes slides)."
---



## Introduction {background="#00100F"}
  
### Lecture Info {background="#43464B" visibility="uncounted"}


#### Learning Outcomes

This lecture is 
<br>

By the end, you should be able to

- Discuss  

#### References

<br>

::: {.nonincremental}

- Chapter 1-2 in @James2023IntroductionStatisticalLearning
- Or chapter 1 in @Mohri2018FoundationsMachineLearning (more examples, shorter)
- Or chapter 1 in @Geron2023HandsonMachineLearning (more examples, longer)

:::  




## Statistical and Machine Learning {background="#00100F"}
  

### Definitions {background="#43464B" visibility="uncounted"}

#### The Two Faces of Statistics

<br> 

Can split statistics into two blocks based on *overall goal*:



1. *Causal inference*: answering counterfactual question regarding causal effects of interventions
2. *Predictions*: finding predictive functions of data without explaining mechanisms




#### Statistical and Machine Learning

Prediction studied by *statistical* and *machine learning*. 

. . . 

Personal definition:

<div class="rounded-box">

::: {#def-pred-learning}


- *Statistical* learning is a branch of statistics studying prediction problems. 
- *Machine* learning is cross-disciplinary subfield of statistics and computer science studying prediction problems. 
 
:::

</div> 

::: {.footer}

Both  develop algorithms that can learn from data and generalize to unseen data

:::


#### Goals in Prediction


<div class="rounded-box">

Key goal of prediction --- predicting <span class="highlight">well</span>

</div> 

Other goals:

- Computational efficiency: better to have a cheaper and quicker way to produce a new prediction
- Interpretability: why is the algorithm predicting what it does?
- Scalability: can it handle increasing loads, run in  distributed manner, etc


 


#### SL vs. Causal Inference II

Goals in causal inference

#### SL vs. Causal Inference II

Are the two disjoint? 

No, often

## References on SL/ML {background="#00100F"}

####

#### Core Books: Theory

 

#### Core Books: Practice



::: {.footer}

Many more field-specific references

:::

#### Books On SL/ML For Causal Settings

## Learning Scenarios {background="#00100F"}
 

#### Introduction to Learning Scenarios

SL/ML not monolithic: there are different learning scenarios based on

- Domain of application: what problem are you solving?
- Nature and form of training data
    - Do you have a $Y$ at all? (supervised, unsupervised, semi-supervised learning, ...)
    - What does $Y$ look like? (continuous --- regression, discrete --- classification, ranked list --- ranking, ...)
- How the data arrives


#### Classification: By Domain {.scrollable}

What kind of problems can you solve? 

| Domain of Application      | Examples                                                                                                         |
|---------------------------|------------------------------------------------------------------------------------------------------------------|
| Forecasting | Estimating the GDP in the current quarter |
| Causal inference | Preestimating "first stage"/nuisance parameters |
| Text or document classification | Assigning topics, determining whether contents are inappropriate, spam detection                           |
| NLP                       | Part-of-speech tagging, named-entity recognition, context-free parsing, text summarization, chatbots              |
| Speech processing         | Speech recognition, speech synthesis, speaker verification and identification                                 |
| Computer vision           | Object recognition and identification, face detection, content-based image retrieval, optical character recognition, image segmentation |
| Anomaly detection         | Detecting credit card fraud                                                                                       |
| Clustering                | Segmenting clients into blocks and offering different marketing strategies                                        |
| Data visualization        | Using dimensionality reduction                                                                                    |
| Recommender systems       | Suggesting next product to buy given purchase history                                                             |

All these things also done with people with econ backgrounds

::: {.footer}

:::


#### Classification: By Type of Output Variable I {.scrollable}

*Supervised settings*: some observed output $Y$: 

<br> 

| Task | Type of Variable | Examples |
| --- | --- | --- |
| Classification | Categorical | Document classification |
| Regression | Continuous | Nowcasting the GDP |
| Ranking | Ordinal | Selecting the order of results in a search | 

::: {.footer}


::: 



#### Classification: By Type of Output Variable II {.scrollable}

*Unsupervised settings*: no obvious observed  $Y$: 

| Task | Type of Variable | Examples |
| --- | --- | --- | 
| Clustering | Categorical | Identifying communities in a large social network |
| Dimensionality reduction/manifold learning | Continuous | Preprocessing digital images in computer vision tasks |

::: {.footer}


::: 


#### Classification: By Supervision

<br> 

- Supervised: all observations ("examples") have $Y$ available ("labels")
- Unsupervised: no examples have labels 
- Semi-supervised: some examples have labels

. . .

More concepts: self-supervised, active learning, reinforcement learning, etc.

#### Online vs. Batch Learning

Another axis: if new observations arrive, how to update model? 

<br>

- Retrain from scratch on bigger dataset --- batch learning
- Update existing model parameters only with new observations --- online learning

 



## Recap and Conclusions {background="#00100F"}
  
#### Recap

<br>

In this lecture we

1. Introduction

#### Next Questions

<br>

- What  

#### References {.allowframebreaks visibility="uncounted"}

::: {#refs}
:::

::: footer

:::

 

 