project:
  type: website
  output-dir: ../docs/

html-math-method: mathjax

website:
  title: "Advanced Econometrics"
  favicon: themes/favicon.ico
  site-url: https://vladislav-morozov.github.io/econometrics-2/
  repo-url: https://github.com/vladislav-morozov/econometrics-2/
  repo-subdir: "src" 
  repo-actions: [edit, issue]
  sidebar:
    style: "floating"
    search: true
    contents: 
      - section: "Course Info"
        contents:
        - slides/organizational/intro.qmd  
      - section: "Linear Regression II"
        contents:
        - slides/vector/vector-ols.qmd 
  # navbar:
  #   foreground: white
  #   search: true
  #   left:
  #     - href: index.qmd
  #       text: Home 
  #     - text: "Course Info"
  #       menu:  
  #        - slides/organizational/intro.qmd 
  #     - text: "Linear Regression II"
  #       menu:
  #        - slides/vector/vector-ols.qmd 
  #     # - text: "Panel Data"
  #     #   menu: 
  #     #    - slides/panel/event-studies.qmd

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    include-in-header: themes/mathjax.html
    theme:
      light: [themes/ws_light.scss, themes/block.scss]
      dark: [themes/ws_dark.scss, themes/block.scss]  

bibliography: eco.bib