project:
  type: website
  output-dir: ../docs/

html-math-method: mathjax

website:
  title: "Advanced Econometrics"
  favicon: themes/favicon.ico
  navbar:
    foreground: white
    search: true
    left:
      - href: index.qmd
        text: Home 
      - text: "Organizational Matters"
        menu: 
         - slides/test_presentation.qmd
         - slides/intro.qmd
         - slides/panel_data.qmd
      - text: "Multivariate Regression"
        menu:
         - slides/vector/vector-ols.qmd 
      - text: "Panel Data"
        menu: 
         - slides/panel/event-studies.qmd

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    include-in-header: themes/mathjax.html
    theme:
      light: [themes/ws_light.scss, themes/block.scss]
      dark: [themes/ws_dark.scss, themes/block.scss]  

bibliography: eco.bib