---
title: "Inference II: Nonlinear Hypotheses"
subtitle: "Handling Nonlinearities with the Delta Method"
author: Vladislav Morozov   
format:
  revealjs:
    width: 1150
    slide-number: true
    sc-sb-title: true
    incremental: true   
    logo: ../../themes/favicon.ico
    footer: "A Deeper Look at Linear Regression: Nonlinear Hypotheses and the Delta Method"
    footer-logo-link: "https://vladislav-morozov.github.io/econometrics-2/"
    theme: ../../themes/slides_theme.scss
    toc: TRUE
    toc-depth: 2
    toc-title: Contents
    transition: convex
    transition-speed: fast
slide-level: 4
title-slide-attributes:
    data-background-color: "#045D5D"
    data-footer: " "
filters:
  - reveal-header  
include-in-header: ../../themes/mathjax.html 
highlight-style: tango
---



## Introduction {background="#00100F"}
  
### Lecture Info {background="#43464B" visibility="uncounted"}


#### Learning Outcomes

This lecture is about 

<br>

By the end, you should be able to

-  

#### References
 

<br>

::: {.nonincremental}

 
- Corresponding [section](https://en.wikipedia.org/wiki/Delta_method) on Wikipedia (Up to the "Example" section)
- *Or* 6.5, 7.10 in @Hansen2022Econometrics

::: 

 

### Reminder on the Empirical Example {background="#43464B" visibility="uncounted"}

#### Reminder: Empirical Model

Studying link between wages and (education, experience)
$$
\begin{aligned}[]
& [\ln(\text{wage}_i)]^{\text{(education, experience)}} \\
&  =   \beta_1 + \beta_2 \times \text{education} \\
& \quad  + \beta_3 \times  \text{experience} + \beta_4 \times  \dfrac{\text{experience}^2}{100} + U_i
\end{aligned}
$$ {#eq-vector-inference-emp-model}


#### Reminder: Estimation Results

#### Parameter of Interest: Nonlinear Transformation

We still have one parameter of interest to look at:
$$
\theta = -50\frac{\beta_3}{\beta_4}
$$

- Interpretation: experience level that maximizes expected log wage
- This $\theta$: <span class="highlight">smooth nonlinear transformation</span> of $\bbeta$

. . . 

<div class="rounded-box">

How to do inference on such $\theta$?

</div>



## The Delta Method  {background="#00100F"}

### Scalar Case {background="#43464B" visibility="uncounted"}

 
#### Mean Value Theorem

Recall the following useful result:

<div class="rounded-box">

::: {#prp-vector-inference-mean-value}

Let $f(\cdot): \R\to\R$ be differentiable on the interval $[x, y]$. Then there exists some $\tilde{y}\in[x, y]$ such that
$$
f(y)-f(x) = f'(\tilde{y})(y-x)
$$


:::

</div>

. . . 

Rearranged: the "mean value expansion around $x$"
$$
f(y) = f(x) + f'(\tilde{y})(y-x)
$$


#### Manual Illustration of the Argument

Let $X_1, \dots, X_N\sim$IID$(\theta, \sigma^2)$ Then $\sqrt{N}(\bar{X}-\theta)\xrightarrow{d} N(0, \sigma^2)$

<div class="rounded-box">

What is the asymptotic distribution of $(\bar{X})^2$?

</div>

. . .

Mean value theorem (@prp-vector-inference-mean-value):
$$
(\bar{X})^2 = \theta^2 + 2(\theta+\alpha_N[\bar{X}-\theta])(\bar{X}-\theta), \quad \alpha_N\in[0, 1]
$$ {#eq-vector-inference-manual-delta}

. . . 

By Slutsky's theorem 
$$
\sqrt{N}(\bar{X}^2 - \theta^2) \xrightarrow{d} N( 0, (2\theta)^2 \sigma^2  )
$$

#### More Abstract Form of ([-@eq-vector-inference-manual-delta])


Can write @eq-vector-inference-manual-delta as 
$$
\sqrt{N}(f(Y_N)-f(\theta)) = f'(\theta + \alpha_N[Y_N-\theta] ) \sqrt{N}(Y_N-\theta)
$$
for 

- $f(y) = y^2$ 
- $Y_N = \bar{X}$
 
#### Abstracting the Argument

<br> 

Can replicate the argument if 

- $Y_N\xrightarrow{p} \theta$ and $f'(\cdot)$ is continuous with $f'(\theta)\neq 0$
- $\sqrt{N}(Y_N-\theta)$ converges to a normal distribution


#### Delta Method in the Univariate Case


Combining the previous arguments gives:
<div class="rounded-box">

::: {#prp-vector-inference-delta-1d}

Let $\sqrt{N}(Y_N-\theta)\xrightarrow{d} N(0, \sigma^2)$ and let $f(\cdot)$ be continuously differentiable. Then
 
$$
\sqrt{N}(f(Y_N) - f(\theta)) \xrightarrow{d} N(0, [f'(\theta)]^2\sigma^2)
$$


:::

</div>
More properly called the <span class="highlight">first-order</span> delta method — there are higher-order versions if $f'(\theta)=0$


### Multivariate Case {background="#43464B" visibility="uncounted"}

#### Motivation
 
@prp-vector-inference-delta-1d has two limitations:

- $Y_N$ is scalar, but we deal with whole vector $\hat{\bbeta}$
- $f(\cdot)$ is scalar-valued — but we may have multiple transformations of $\bbeta$

. . . 

<br>

Can solve both! Let $\ba(\bbeta):\R^p\to\R^q$ be the transformation of interest

#### Jacobian of $\ba(\cdot)$

Let $\ba(\cdot) = (a_1(\cdot), \dots, a_q(\cdot))'$. Define its *Jacobian matrix* $\bA(\bbeta)$ as 
$$
\bA(\bbeta) = \begin{pmatrix}
\frac{\partial a_1}{\partial \beta_1}(\bbeta) & \cdots & \frac{\partial a_1}{\partial \beta_p}(\bbeta)\\
\vdots & \ddots & \vdots\\
\frac{\partial a_q}{\partial \beta_1}(\bbeta) & \cdots & \frac{\partial a_q}{\partial \beta_p}(\bbeta) 
\end{pmatrix}
$$ 
 Rows correspond to components of $\ba(\cdot)$; columns — to components of $\bbeta$

#### Delta Method in the Multivariate Case

  
<div class="rounded-box">

::: {#prp-vector-inference-delta}

Let $\sqrt{N}(\bY_N-\btheta)\xrightarrow{d} N(0, \bSigma)$. Let $\ba(\cdot)$ be continuously differentiable. Let $\bA(\btheta)$ have rank $q$. Then
 
$$
\sqrt{N}(\ba(\bY_N) - \ba(\btheta)) \xrightarrow{d} N(0, \bA(\btheta)\bSigma\bA(\btheta)')
$$


:::

</div>

- Proof (not examinable) is similar to the univariate case
- OLS: take $\bY_N=\hat{\bbeta}$ and $\btheta=\bbeta$

#### Vector Example I: Norm of $\bbeta$

Suppose that our parameter of interest is $\ba(\bbeta) = \norm{\bbeta}$. Then 
$$
\bA(\bbeta) = \begin{pmatrix}
\dfrac{\beta_1}{\norm{\bbeta}}  & \cdots & \dfrac{\beta_p}{\norm{\bbeta}}
\end{pmatrix}
$$

. . .

If $\bbeta\neq 0$, the delta method (@prp-vector-inference-delta) tells us that 
$$
\sqrt{N}(\norm{\hat{\bbeta}}-\norm{\bbeta})\xrightarrow{d} N(0, \bA(\bbeta)\avar(\bbeta)\bA(\bbeta)')
$$


#### Vector Example II: Linear Transformations

Another example: $\ba(\bbeta) = \bR\bbeta$. Then $\bA(\bbeta)=\bR$ and 

. . .

$$
\sqrt{N}(\bR\hat{\bbeta}-\bR\bbeta)\xrightarrow{d} N(0, \bR\avar(\bbeta)\bR')
$$

<br>

In words, the delta method implies our results for linear transformations from before 


#### Generalizations 

Delta method — extremely general tool!

<br>

Some generalizations:

- The limit does not have to be normal
- Speed of convergence does not have to be $\sqrt{N}$
- $f(\cdot)$ can have functions as inputs and outputs


## Inference on Nonlinear Transformations {background="#00100F"}


### Confidence Intervals {background="#43464B" visibility="uncounted"}

#### Overall Idea

Can use @prp-vector-inference-delta for inference!

. . . 

<br>

Intuitively, it says that 
$$
\ba(\hat{\bbeta}) \overset{a}{\sim} N\left(\ba(\bbeta), \dfrac{1}{N}\bA(\bbeta)\avar(\bbeta)\bA(\bbeta)'  \right)
$$

Can construct tests and confidence intervals same way as before, just need to compute the Jacobian $\bA$


#### Estimating the Asymptotic Variance 

For construction, need to estimate 
$$
\avar(\ba(\hat{\bbeta})) = \bA(\bbeta)\avar(\bbeta)\bA(\bbeta)'
$$

To consistently estimate it

- Estimate $\avar(\hat{\bbeta})$ as before with HC0 (or other robust) errors $\widehat{\avar}(\hat{\bbeta})$
- For $\bA(\bbeta)$, just use $\bA(\hat{\bbeta})$



#### Example: Confidence Interval for Ratio


Suppose that $\bbeta=(\beta_1, \beta_2)$, $\beta_2\neq 0$, and $a(\bbeta) = \beta_1/\beta_2$

. . .

<br> 

As in the previous lecture, the following is $(1-\alpha)\times 100\%$ asymptotic confidence interval 
$$ \small
S = \left[ \dfrac{\hat{\beta}_1}{\hat{\beta_2}} - z_{1-\alpha/2} \sqrt{\dfrac{\widehat{\avar}(\hat{\beta}_1/\hat{\beta}_2)}{N}  } ,  \dfrac{\hat{\beta}_1}{\hat{\beta_2}} + z_{1-\alpha/2} \sqrt{\dfrac{\widehat{\avar}(\hat{\beta}_1/\hat{\beta}_2)}{N}  } \right]
$$

#### Example: Estimating $\widehat{\avar}(\hat{\beta}_1/\hat{\beta}_2)$

Jacobian of our $a(\cdot)$ is
$$
\bA(\bbeta) = \begin{pmatrix}
1/\beta_2 & -\beta_1/\beta_2^2
\end{pmatrix}
$$
$\bA(\bbeta)$ defined and maximal rank if $\beta_2\neq 0$

. . . 

So

$$
\widehat{\avar}(\hat{\beta}_1/\hat{\beta}_2) = \begin{pmatrix}
1/\hat{\beta}_2 & -\hat{\beta}_1/\hat{\beta}_2^2
\end{pmatrix}\widehat{\avar}(\hat{\bbeta}) \begin{pmatrix}
1/\hat{\beta}_2 \\ -\hat{\beta}_1/\hat{\beta}_2^2
\end{pmatrix}
$$

#### Application to Empirical Parameter

Our empirical parameter of interest was 
$$
\ba(\bbeta) = -50\beta_3/\beta_4
$$

Here Jacobian is

. . .

$$
\bA(\bbeta) = \begin{pmatrix}
0 & 0 & -50/\beta_4 & 50\beta_3/\beta_4^2
\end{pmatrix}
$$


#### The Delta Method in `statsmodels`

Can use the Delta method in `statsmodels` using the `NonlinearDeltaCov` class — compatible with many different models and estimators, not just OLS.

. . .

 To define an instance, need

- Function $\ba(\cdot)$
- $\hat{\bbeta}$ and $N^{-1}\widehat{\avar}(\hat{\bbeta})$ (standard errors)
- (*Optionally*): function for $\bA(\cdot)$

#### Documentation of `NonlinearDeltaCov`

Functionality not documented, but [in code](https://github.com/statsmodels/statsmodels/blob/main/statsmodels/stats/_delta_method.py) with good docstrings

#### Creating an Instance of `NonlinearDeltaCov`

In our example, define the function $a(\cdot)$


Then we supply $a(\cdot)$ together with parameters and standard errors:


#### Constructing Confidence Intervals with `NonlinearDeltaCov`

Can construct a 95\% confidence interval with the `conf_int()` method

or the `summary()` method


### Nonlinear Wald Tests {background="#43464B" visibility="uncounted"}

#### Hypotheses

What 

If there are any constants, they are absorbed into the definition of $\ba$

#### Example:


#### Wald Statistic

We can use the same idea as before


#### Wald Test


####

In fact, this matches exactly the Wald and $t$ tests for linear hypotheses (check this!)

## Recap and Conclusions {background="#00100F"}
  
#### Recap

In this lecture we

1. A
   
#### Overall Concluding Thoughts on the Block

<br>

1. Deep analysis of the linear model, and linear models appear naturally in some settings, as we will see in the next block
1. But also the tools are quite general asymptotic tools are very general
2. The overall approach to constructing tests and CIs works similarly
  

#### References {.allowframebreaks visibility="uncounted"}

::: {#refs}
:::